version: "3.9"
services:
  postgres:
    image: postgres:16.0-alpine3.18
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: threadsAPI_DB
    networks:
      - threadsAPI_networt
networks:
  threadsAPI_networt: